use std::collections::HashMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use dashmap::DashMap;
use std::sync::LazyLock;
use tokio::sync::Mutex;

use crate::errors::{MhError, MhResult};

pub fn cookie_expiry(path: &Path, name: &str, domain_suffix: Option<&str>) -> Option<Option<i64>> {
    let txt = fs::read_to_string(path).ok()?;
    for line in txt.lines() {
        let line = line.trim_start();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let parts: Vec<&str> = line.split('\t').collect();
        if parts.len() < 7 {
            continue;
        }
        if parts[5] != name {
            continue;
        }
        if let Some(suffix) = domain_suffix {
            let dom = parts[0].trim_start_matches('.');
            let want = suffix.trim_start_matches('.');
            if !(dom == want || dom.ends_with(&format!(".{want}"))) {
                continue;
            }
        }
        let exp: i64 = parts[4].parse().unwrap_or(0);
        return Some(if exp > 0 { Some(exp) } else { None });
    }
    None
}

#[derive(Debug, Clone, PartialEq)]
pub struct CookieRow {
    pub domain: String,
    pub include_subdomains: bool,
    pub path: String,
    pub secure: bool,
    pub expires: i64,
    pub name: String,
    pub value: String,
}

impl CookieRow {
    fn to_line(&self) -> String {
        format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}",
            self.domain,
            if self.include_subdomains {
                "TRUE"
            } else {
                "FALSE"
            },
            self.path,
            if self.secure { "TRUE" } else { "FALSE" },
            self.expires,
            self.name,
            self.value,
        )
    }
}

pub fn parse_all(path: &Path) -> MhResult<Vec<CookieRow>> {
    let txt = fs::read_to_string(path).map_err(MhError::Io)?;
    let mut rows = Vec::new();
    for line in txt.lines() {
        let raw = line.trim_end_matches(['\r', '\n']);
        let trimmed = raw.trim_start();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let parts: Vec<&str> = raw.split('\t').collect();
        if parts.len() < 7 {
            continue;
        }
        rows.push(CookieRow {
            domain: parts[0].to_string(),
            include_subdomains: parts[1].eq_ignore_ascii_case("TRUE"),
            path: parts[2].to_string(),
            secure: parts[3].eq_ignore_ascii_case("TRUE"),
            expires: parts[4].parse().unwrap_or(0),
            name: parts[5].to_string(),
            value: parts[6..].join("\t"),
        });
    }
    Ok(rows)
}

pub fn serialize(rows: &[CookieRow]) -> String {
    let mut out = String::from("# Netscape HTTP Cookie File\n");
    out.push_str("# This file is generated by MediaHarbor. Edit at your own risk.\n\n");
    for r in rows {
        out.push_str(&r.to_line());
        out.push('\n');
    }
    out
}

fn norm_domain(d: &str) -> &str {
    d.trim_start_matches('.')
}

struct ParsedSetCookie {
    name: String,
    value: String,
    domain: Option<String>,
    path: Option<String>,
    secure: bool,
    expires: Option<i64>,
}

fn parse_set_cookie(header: &str) -> Option<ParsedSetCookie> {
    let mut parts = header.split(';');
    let nv = parts.next()?.trim();
    let (name, value) = nv.split_once('=')?;
    let name = name.trim();
    if name.is_empty() {
        return None;
    }
    let mut out = ParsedSetCookie {
        name: name.to_string(),
        value: value.trim().to_string(),
        domain: None,
        path: None,
        secure: false,
        expires: None,
    };
    let mut max_age: Option<i64> = None;
    let mut expires_attr: Option<i64> = None;
    for attr in parts {
        let attr = attr.trim();
        if attr.eq_ignore_ascii_case("Secure") {
            out.secure = true;
            continue;
        }
        let Some((k, v)) = attr.split_once('=') else {
            continue;
        };
        let (k, v) = (k.trim(), v.trim());
        if k.eq_ignore_ascii_case("Domain") {
            out.domain = Some(v.to_string());
        } else if k.eq_ignore_ascii_case("Path") {
            out.path = Some(v.to_string());
        } else if k.eq_ignore_ascii_case("Max-Age") {
            if let Ok(secs) = v.parse::<i64>() {
                max_age = Some(chrono::Utc::now().timestamp() + secs);
            }
        } else if k.eq_ignore_ascii_case("Expires") {
            expires_attr = parse_http_date(v);
        }
    }
    out.expires = max_age.or(expires_attr);
    Some(out)
}

fn parse_http_date(s: &str) -> Option<i64> {
    const FORMATS: [&str; 3] = [
        "%a, %d %b %Y %H:%M:%S GMT",
        "%a, %d-%b-%Y %H:%M:%S GMT",
        "%a, %d-%b-%y %H:%M:%S GMT",
    ];
    for fmt in FORMATS {
        if let Ok(dt) = chrono::NaiveDateTime::parse_from_str(s, fmt) {
            return Some(dt.and_utc().timestamp());
        }
    }
    None
}

static WRITE_LOCKS: LazyLock<DashMap<PathBuf, Arc<Mutex<()>>>> = LazyLock::new(DashMap::new);

fn lock_for(path: &Path) -> Arc<Mutex<()>> {
    WRITE_LOCKS
        .entry(path.to_path_buf())
        .or_insert_with(|| Arc::new(Mutex::new(())))
        .clone()
}

pub async fn apply_set_cookies(path: &Path, set_cookies: &[String]) -> MhResult<bool> {
    if set_cookies.is_empty() {
        return Ok(false);
    }
    let lock = lock_for(path);
    let _guard = lock.lock().await;

    let mut rows = parse_all(path)?;
    let mut index: HashMap<(String, String), usize> = HashMap::new();
    for (i, r) in rows.iter().enumerate() {
        index.insert((r.name.clone(), norm_domain(&r.domain).to_string()), i);
    }

    let mut changed = false;
    for header in set_cookies {
        let Some(sc) = parse_set_cookie(header) else {
            continue;
        };
        let match_domain = sc
            .domain
            .as_deref()
            .map(|d| norm_domain(d).to_string())
            .or_else(|| {
                rows.iter()
                    .find(|r| r.name == sc.name)
                    .map(|r| norm_domain(&r.domain).to_string())
            });
        let Some(match_domain) = match_domain else {
            continue;
        };

        match index.get(&(sc.name.clone(), match_domain.clone())) {
            Some(&i) => {
                let row = &mut rows[i];
                if row.value != sc.value {
                    row.value = sc.value.clone();
                    changed = true;
                }
                if let Some(exp) = sc.expires {
                    if row.expires != exp {
                        row.expires = exp;
                        changed = true;
                    }
                }
            }
            None => {
                let domain = sc
                    .domain
                    .clone()
                    .unwrap_or_else(|| format!(".{match_domain}"));
                rows.push(CookieRow {
                    include_subdomains: domain.starts_with('.'),
                    domain,
                    path: sc.path.clone().unwrap_or_else(|| "/".to_string()),
                    secure: sc.secure,
                    expires: sc.expires.unwrap_or(0),
                    name: sc.name.clone(),
                    value: sc.value.clone(),
                });
                index.insert((sc.name.clone(), match_domain), rows.len() - 1);
                changed = true;
            }
        }
    }

    if !changed {
        return Ok(false);
    }

    let content = serialize(&rows);
    let dir = path.parent().unwrap_or_else(|| Path::new("."));
    let mut tmp = tempfile::NamedTempFile::new_in(dir).map_err(MhError::Io)?;
    tmp.write_all(content.as_bytes()).map_err(MhError::Io)?;
    tmp.persist(path).map_err(|e| MhError::Io(e.error))?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn parses_expiry() {
        let mut f = tempfile::NamedTempFile::new().unwrap();
        writeln!(f, "# Netscape").unwrap();
        writeln!(f, ".youtube.com\tTRUE\t/\tTRUE\t9999999999\tSAPISID\tabc").unwrap();
        let exp = cookie_expiry(f.path(), "SAPISID", Some("youtube.com"));
        assert_eq!(exp, Some(Some(9999999999)));
    }

    #[test]
    fn session_cookie() {
        let mut f = tempfile::NamedTempFile::new().unwrap();
        writeln!(f, ".x.com\tTRUE\t/\tTRUE\t0\tFOO\tbar").unwrap();
        assert_eq!(cookie_expiry(f.path(), "FOO", Some("x.com")), Some(None));
    }

    #[test]
    fn missing_cookie() {
        let mut f = tempfile::NamedTempFile::new().unwrap();
        writeln!(f, ".x.com\tTRUE\t/\tTRUE\t1\tBAZ\tq").unwrap();
        assert_eq!(cookie_expiry(f.path(), "FOO", Some("x.com")), None);
    }

    #[test]
    fn parse_all_round_trips() {
        let mut f = tempfile::NamedTempFile::new().unwrap();
        writeln!(f, "# Netscape HTTP Cookie File").unwrap();
        writeln!(f, ".youtube.com\tTRUE\t/\tTRUE\t1814862820\tSAPISID\tabc").unwrap();
        writeln!(f, ".google.com\tTRUE\t/\tFALSE\t0\tSIDCC\txyz").unwrap();
        let rows = parse_all(f.path()).unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].name, "SAPISID");
        assert_eq!(rows[0].value, "abc");
        assert!(rows[0].secure);
        assert_eq!(rows[1].name, "SIDCC");
        assert!(!rows[1].secure);
        let serialized = serialize(&rows);
        std::fs::write(f.path(), &serialized).unwrap();
        assert_eq!(parse_all(f.path()).unwrap(), rows);
    }

    #[test]
    fn parse_set_cookie_extracts_fields() {
        let sc = parse_set_cookie(
            "__Secure-3PSIDTS=NEWVAL; Domain=.youtube.com; Path=/; Secure; HttpOnly; SameSite=None; Max-Age=3600",
        )
        .unwrap();
        assert_eq!(sc.name, "__Secure-3PSIDTS");
        assert_eq!(sc.value, "NEWVAL");
        assert_eq!(sc.domain.as_deref(), Some(".youtube.com"));
        assert!(sc.secure);
        assert!(sc.expires.is_some());
    }

    #[tokio::test]
    async fn apply_set_cookies_upserts_and_preserves() {
        let mut f = tempfile::NamedTempFile::new().unwrap();
        writeln!(f, "# Netscape HTTP Cookie File").unwrap();
        writeln!(f, ".youtube.com\tTRUE\t/\tTRUE\t100\t__Secure-3PSIDTS\tOLD").unwrap();
        writeln!(f, ".other.com\tTRUE\t/\tFALSE\t0\tKEEP\tme").unwrap();

        let headers = vec![
            "__Secure-3PSIDTS=ROTATED; Domain=.youtube.com; Path=/; Secure".to_string(),
            "SIDCC=fresh; Domain=.youtube.com; Path=/".to_string(),
        ];
        let changed = apply_set_cookies(f.path(), &headers).await.unwrap();
        assert!(changed);

        let rows = parse_all(f.path()).unwrap();
        let sidts = rows.iter().find(|r| r.name == "__Secure-3PSIDTS").unwrap();
        assert_eq!(sidts.value, "ROTATED");
        assert!(rows.iter().any(|r| r.name == "SIDCC" && r.value == "fresh"));
        assert!(rows
            .iter()
            .any(|r| r.domain == ".other.com" && r.value == "me"));

        let changed_again = apply_set_cookies(f.path(), &headers).await.unwrap();
        assert!(!changed_again);
    }
}
