export interface Settings {
  schemaVersion?: number;
  autoUpdate: boolean;
  autoDownloadUpdates: boolean;
  theme: 'auto' | 'dark' | 'light';
  downloadLocation: string;
  createPlatformSubfolders: boolean;
  orpheusDL: boolean;

  enabledServices: string[];
  radioDirectorySources: string[];

  use_cookies: boolean;
  cookies: string;
  cookies_from_browser: string;
  ytdlp_cookies_path: string;
  youtube_cookies_path: string;
  ytmusic_cookies_path: string;
  ytmusic_sync_playback_history: boolean;
  yt_override_download_extension: boolean;
  ytm_override_download_extension: boolean;
  youtubeVideoExtensions: string;
  youtubeAudioExtensions: string;
  use_aria2: boolean;
  max_downloads: number;
  download_speed_limit: boolean;
  speed_limit_type: string;
  speed_limit_value: number;
  max_retries: number;
  download_output_template: string;
  continue: boolean;
  add_metadata: boolean;
  embed_chapters: boolean;
  add_subtitle_to_file: boolean;
  use_proxy: boolean;
  proxy_url: string;
  use_authentication: boolean;
  username: string;
  password: string;
  sponsorblock_mark: string;
  sponsorblock_remove: string;
  sponsorblock_chapter_title: string;
  no_sponsorblock: boolean;
  sponsorblock_api_url: string;

  concurrent_fragments: number;
  remux_format: string;
  convert_thumbnails_jpg: boolean;
  sub_langs: string;
  write_auto_subs: boolean;
  convert_subs_srt: boolean;
  fragment_retries: string;
  extractor_retries: string;
  file_access_retries: string;
  socket_timeout: number;
  throttled_rate: string;
  sleep_requests: string;
  sleep_interval: string;
  max_sleep_interval: string;
  aria2c_args: string;
  postprocessor_args: string;
  faststart_mp4: boolean;
  trim_filenames: number;
  restrict_filenames: boolean;
  windows_filenames: boolean;
  no_overwrites: boolean;
  geo_bypass_country: string;
  set_mtime: boolean;
  player_client: string;
  ejs_remote_components: string;
  pot_provider_enabled: boolean;
  po_token: string;
  pot_trace: boolean;
  extra_args: string;

  disc_subdirectories: boolean;
  save_playlist_file: boolean;

  qobuz_quality: number;
  qobuz_download_booklets: boolean;
  qobuz_email_or_userid: string;
  qobuz_password_or_token: string;
  qobuz_app_id: string;
  qobuz_app_secret: string;
  qobuz_secrets: string;
  qobuz_telemetry_enabled: boolean;
  qobuz_sync_playback_history: boolean;
  qobuz_filters_extras: boolean;
  qobuz_repeats: boolean;
  qobuz_non_albums: boolean;
  qobuz_features: boolean;
  qobuz_non_studio_albums: boolean;
  qobuz_non_remaster: boolean;

  tidal_quality: number;
  tidal_telemetry_enabled: boolean;
  tidal_sync_playback_history: boolean;
  tidal_device_model: string;
  tidal_device_vendor: string;
  tidal_device_type: string;
  tidal_os_version: string;
  tidal_screen_width: number;
  tidal_screen_height: number;
  tidal_download_videos: boolean;
  tidal_video_quality: string;
  tidal_user_id: string;
  tidal_country_code: string;
  tidal_access_token: string;
  tidal_refresh_token: string;
  tidal_token_expiry: string;
  tidal_client_id: string;
  tidal_client_secret: string;

  deezer_quality: string;
  deezer_arl: string;
  deezer_lrc_public_fallback: boolean;
  deezer_telemetry_enabled: boolean;
  deezer_sync_playback_history: boolean;

  conversion_check: boolean;
  conversion_codec: string;
  conversion_sampling_rate: number | null;
  conversion_bit_depth: number | null;
  conversion_lossy_bitrate: number;

  meta_exclude_tags_check: boolean;
  excluded_tags: string;

  filepaths_folder_format: string;
  filepaths_track_format: string;
  filepaths_restrict_characters: boolean;
  filepaths_truncate_to: number;

  embed_cover: boolean;
  save_cover: boolean;
  save_album_cover: boolean;
  pipeline_cover_size: number;
  pipeline_overwrite: boolean;
  save_lrc_files: boolean;
  lyrics_fallback_lrclib: boolean;
  native_synced_lyrics_format: string;
  embed_lyrics: boolean;

  youtube_quality: number;
  youtube_api_key: string;

  spotify_client_id: string;
  spotify_client_secret: string;
  spotify_cookies_path: string;
  spotify_output_path: string;
  spotify_audio_quality: string;
  spotify_sync_playback_history: boolean;
  spotify_telemetry_enabled: boolean;
  spotify_audio_download_mode: string;
  spotify_audio_remux_mode: string;
  spotify_video_format: string;
  spotify_video_resolution: string;
  spotify_video_remux_mode: string;
  spotify_cover_size: string;
  spotify_wvd_path: string;
  spotify_no_drm: boolean;
  spotify_wait_interval: number;
  spotify_overwrite: boolean;
  spotify_no_synced_lyrics_file: boolean;
  spotify_save_playlist_file: boolean;
  spotify_save_cover_file: boolean;
  spotify_synced_lyrics_only: boolean;
  spotify_album_folder_template: string;
  spotify_compilation_folder_template: string;
  spotify_podcast_folder_template: string;
  spotify_no_album_folder_template: string;
  spotify_single_disc_file_template: string;
  spotify_multi_disc_file_template: string;
  spotify_podcast_file_template: string;
  spotify_no_album_file_template: string;
  spotify_playlist_file_template: string;
  spotify_date_tag_template: string;
  spotify_truncate: number;
  spotify_exclude_tags: string;
  spotify_log_level: string;
  spotify_no_exceptions: boolean;
  spotify_artist_media_option: string;
  spotify_prefer_video: boolean;
  spotify_session_type: string;
  spotify_dll_path: string;

  spotify_downloader_backend: string;
  spotify_native_quality: string;
  native_skip_existing: boolean;

  apple_cookies_path: string;
  apple_output_path: string;
  apple_temp_path: string;
  apple_download_mode: string;
  apple_cover_format: string;
  apple_cover_size: number;
  apple_save_cover: boolean;
  apple_sync_playback_history: boolean;
  apple_synced_lyrics_format: string;
  apple_synced_lyrics_only: boolean;
  apple_no_synced_lyrics: boolean;
  apple_template_folder_album: string;
  apple_template_folder_compilation: string;
  apple_template_file_single_disc: string;
  apple_template_file_multi_disc: string;
  apple_template_folder_no_album: string;
  apple_template_file_no_album: string;
  apple_template_file_playlist: string;
  apple_date_tag_template: string;
  apple_save_playlist: boolean;
  apple_overwrite: boolean;
  apple_language: string;
  apple_truncate: number;
  apple_exclude_tags: string;
  apple_log_level: string;
  apple_use_album_date: boolean;
  apple_no_exceptions: boolean;
  apple_mv_codec_priority: string;
  apple_mv_remux_format: string;
  apple_mv_resolution: string;
  apple_uploaded_video_quality: string;
  apple_nm3u8dlre_path: string;
  apple_ffmpeg_path: string;
  apple_wvd_path: string;
  apple_use_wrapper: boolean;
  apple_wrapper_url: string;
  apple_wrapper_decrypt_host: string;
  apple_wrapper_decrypt_port: string;
  apple_wrapper_email: string;
  apple_wrapper_password: string;
  apple_artist_auto_select: string;
  apple_playlist_folder_template: string;

  apple_downloader_backend: string;
  apple_native_quality: string;

  orpheus_dl_enabled_modules: string;
  orpheus_custom_modules: string;

  replaygain_mode: string;
  crossfade_enabled: boolean;
  crossfade_duration: number;

  onboarding_completed: boolean;
}

export type SettingsSetter = (key: keyof Settings, value: unknown) => void;
