# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Electron workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Build the project
      - run: npm run build --if-present

  release:

    runs-on: ubuntu-latest

    needs: build

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Create release with source code only
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*.js
            **/*.json
            **/*.html
            **/*.css
          body: |
            ## Changelog
            $(git log -1 --pretty=format:"%h - %s (%an, %ad)")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}